In [23]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("synthetic_fraud_dataset.csv")

In [4]:
df.head()

,transaction_id,user_id,amount,transaction_type,merchant_category,country,hour,device_risk_score,ip_risk_score,is_fraud
0,9608,363,4922.587542,ATM,Travel,TR,12,0.992347,0.947908,1
1,456,692,48.018303,QR,Food,US,21,0.168571,0.224057,0
2,4747,587,136.881960,Online,Travel,TR,14,0.296127,0.125058,0
3,6934,445,80.534719,POS,Clothing,TR,23,0.124801,0.159243,0
4,1646,729,120.041158,Online,Grocery,FR,16,0.098129,0.027542,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_id     10000 non-null  int64
 1   user_id            10000 non-null  int64
 2   amount             10000 non-null  float64
 3   transaction_type   10000 non-null  object
 4   merchant_category  10000 non-null  object
 5   country            10000 non-null  object
 6   hour               10000 non-null  int64
 7   device_risk_score  10000 non-null  float64
 8   ip_risk_score      10000 non-null  float64
 9   is_fraud           10000 non-null  int64
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB

In [6]:
df.describe()

,transaction_id,user_id,amount,hour,device_risk_score,ip_risk_score,is_fraud
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4999.50000,500.058700,178.142763,14.247100,0.183773,0.184669,0.050000
std,2886.89568,288.328495,531.647950,5.347383,0.177381,0.175772,0.217956
min,0.00000,0.000000,1.000000,0.000000,0.000030,0.000009,0.000000
25%,2499.75000,247.000000,65.084753,10.000000,0.075721,0.077762,0.000000
50%,4999.50000,503.000000,101.686510,14.000000,0.156583,0.158290,0.000000
75%,7499.25000,750.250000,138.280872,19.000000,0.234939,0.236968,0.000000
max,9999.00000,999.000000,11628.213881,23.000000,0.998737,0.999603,1.000000

In [9]:
df['transaction_id'].duplicated().sum()

np.int64(0)

In [16]:
df=df.drop(['transaction_id'],axis=1)

In [19]:
y=df['is_fraud']

In [20]:
df.drop(['is_fraud'],axis=1)

,amount,transaction_type,merchant_category,country,hour,device_risk_score,ip_risk_score
0,4922.587542,ATM,Travel,TR,12,0.992347,0.947908
1,48.018303,QR,Food,US,21,0.168571,0.224057
2,136.881960,Online,Travel,TR,14,0.296127,0.125058
3,80.534719,POS,Clothing,TR,23,0.124801,0.159243
4,120.041158,Online,Grocery,FR,16,0.098129,0.027542
...,...,...,...,...,...,...,...
9995,58.366442,POS,Clothing,DE,12,0.066366,0.086344
9996,139.502160,POS,Travel,DE,13,0.119014,0.285680
9997,71.012122,Online,Travel,TR,8,0.119204,0.262262
9998,21.031405,QR,Grocery,UK,12,0.027088,0.295243
9999,54.028632,ATM,Electronics,DE,11,0.096438,0.042823

In [21]:
num_cols=['amount','hour','device_risk_score','ip_risk_score']
cat_cols=['transaction_type','merchant_category','country']

In [26]:
correlations = df[num_cols].corrwith(df['is_fraud'])

In [27]:
print(correlations)

amount               0.638435
hour                -0.181448
device_risk_score    0.871989
ip_risk_score        0.870738
dtype: float64

In [32]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols)
    ],
    remainder='passthrough' # Keep any other columns not specified
)
preprocessor.set_output(transform="pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('num', 'passthrough',
                                 ['amount', 'hour', 'device_risk_score',
                                  'ip_risk_score']),
                                ('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['transaction_type', 'merchant_category',
                                  'country'])])

In [33]:
 transformed_df = preprocessor.fit_transform(df)

In [35]:
print(transformed_df)

      num__amount  num__hour  num__device_risk_score  num__ip_risk_score  \
0     4922.587542         12                0.992347            0.947908
1       48.018303         21                0.168571            0.224057
2      136.881960         14                0.296127            0.125058
3       80.534719         23                0.124801            0.159243
4      120.041158         16                0.098129            0.027542
...           ...        ...                     ...                 ...
9995    58.366442         12                0.066366            0.086344
9996   139.502160         13                0.119014            0.285680
9997    71.012122          8                0.119204            0.262262
9998    21.031405         12                0.027088            0.295243
9999    54.028632         11                0.096438            0.042823

      cat__transaction_type_ATM  cat__transaction_type_Online  \
0                           1.0                           0.0
1                           0.0                           0.0
2                           0.0                           1.0
3                           0.0                           0.0
4                           0.0                           1.0
...                         ...                           ...
9995                        0.0                           0.0
9996                        0.0                           0.0
9997                        0.0                           1.0
9998                        0.0                           0.0
9999                        1.0                           0.0

      cat__transaction_type_POS  cat__transaction_type_QR  \
0                           0.0                       0.0
1                           0.0                       1.0
2                           0.0                       0.0
3                           1.0                       0.0
4                           0.0                       0.0
...                         ...                       ...
9995                        1.0                       0.0
9996                        1.0                       0.0
9997                        0.0                       0.0
9998                        0.0                       1.0
9999                        0.0                       0.0

      cat__merchant_category_Clothing  cat__merchant_category_Electronics  \
0                                 0.0                                 0.0
1                                 0.0                                 0.0
2                                 0.0                                 0.0
3                                 1.0                                 0.0
4                                 0.0                                 0.0
...                               ...                                 ...
9995                              1.0                                 0.0
9996                              0.0                                 0.0
9997                              0.0                                 0.0
9998                              0.0                                 0.0
9999                              0.0                                 1.0

      cat__merchant_category_Food  cat__merchant_category_Grocery  \
0                             0.0                             0.0
1                             1.0                             0.0
2                             0.0                             0.0
3                             0.0                             0.0
4                             0.0                             1.0
...                           ...                             ...
9995                          0.0                             0.0
9996                          0.0                             0.0
9997                          0.0                             0.0
9998                          0.0                             1.0
9999                          0.0                             0.0

      cat__merchant_category_Travel  cat__country_DE  cat__country_FR  \
0                               1.0              0.0              0.0
1                               0.0              0.0              0.0
2                               1.0              0.0              0.0
3                               0.0              0.0              0.0
4                               0.0              0.0              1.0
...                             ...              ...              ...
9995                            0.0              1.0              0.0
9996                            1.0              1.0              0.0
9997                            1.0              0.0              0.0
9998                            0.0              0.0              0.0
9999                            0.0              1.0              0.0

      cat__country_NG  cat__country_TR  cat__country_UK  cat__country_US  \
0                 0.0              1.0              0.0              0.0
1                 0.0              0.0              0.0              1.0
2                 0.0              1.0              0.0              0.0
3                 0.0              1.0              0.0              0.0
4                 0.0              0.0              0.0              0.0
...               ...              ...              ...              ...
9995              0.0              0.0              0.0              0.0
9996              0.0              0.0              0.0              0.0
9997              0.0              1.0              0.0              0.0
9998              0.0              0.0              1.0              0.0
9999              0.0              0.0              0.0              0.0

      remainder__is_fraud
0                       1
1                       0
2                       0
3                       0
4                       0
...                   ...
9995                    0
9996                    0
9997                    0
9998                    0
9999                    0

[10000 rows x 20 columns]

In [36]:
transformed_df

,num__amount,num__hour,num__device_risk_score,num__ip_risk_score,cat__transaction_type_ATM,cat__transaction_type_Online,cat__transaction_type_POS,cat__transaction_type_QR,cat__merchant_category_Clothing,cat__merchant_category_Electronics,cat__merchant_category_Food,cat__merchant_category_Grocery,cat__merchant_category_Travel,cat__country_DE,cat__country_FR,cat__country_NG,cat__country_TR,cat__country_UK,cat__country_US,remainder__is_fraud
0,4922.587542,12,0.992347,0.947908,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1
1,48.018303,21,0.168571,0.224057,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
2,136.881960,14,0.296127,0.125058,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0
3,80.534719,23,0.124801,0.159243,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
4,120.041158,16,0.098129,0.027542,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,58.366442,12,0.066366,0.086344,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
9996,139.502160,13,0.119014,0.285680,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0
9997,71.012122,8,0.119204,0.262262,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0
9998,21.031405,12,0.027088,0.295243,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
9999,54.028632,11,0.096438,0.042823,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0

In [37]:
correlation=transformed_df.corrwith(y)

In [38]:
print(correlation)

num__amount                           0.638435
num__hour                            -0.181448
num__device_risk_score                0.871989
num__ip_risk_score                    0.870738
cat__transaction_type_ATM             0.012192
cat__transaction_type_Online          0.006610
cat__transaction_type_POS            -0.013023
cat__transaction_type_QR             -0.005612
cat__merchant_category_Clothing       0.011395
cat__merchant_category_Electronics   -0.002692
cat__merchant_category_Food          -0.010451
cat__merchant_category_Grocery       -0.004208
cat__merchant_category_Travel         0.006005
cat__country_DE                      -0.031972
cat__country_FR                      -0.031216
cat__country_NG                       0.438086
cat__country_TR                      -0.024890
cat__country_UK                      -0.015300
cat__country_US                      -0.006251
remainder__is_fraud                   1.000000
dtype: float64

In [45]:
correlation['num__amount']

np.float64(0.6384350549014357)

In [52]:
useless=[]
for key in correlation.keys():
    if correlation[key] <= 0:
        useless.append(key)

In [53]:
useless

['num__hour',
 'cat__transaction_type_POS',
 'cat__transaction_type_QR',
 'cat__merchant_category_Electronics',
 'cat__merchant_category_Food',
 'cat__merchant_category_Grocery',
 'cat__country_DE',
 'cat__country_FR',
 'cat__country_TR',
 'cat__country_UK',
 'cat__country_US']

In [64]:
transformed_df=transformed_df.drop(['cat__transaction_type_POS',
 'cat__transaction_type_QR',
 'cat__merchant_category_Electronics',
 'cat__merchant_category_Food',
 'cat__merchant_category_Grocery',
 'cat__country_DE',
 'cat__country_FR',
 'cat__country_TR',
 'cat__country_UK',
 'cat__country_US'],axis=1)

In [67]:
transformed_df.drop('remainder__is_fraud',axis=1)

,num__amount,num__device_risk_score,num__ip_risk_score,cat__transaction_type_ATM,cat__transaction_type_Online,cat__merchant_category_Clothing,cat__merchant_category_Travel,cat__country_NG
0,4922.587542,0.992347,0.947908,1.0,0.0,0.0,1.0,0.0
1,48.018303,0.168571,0.224057,0.0,0.0,0.0,0.0,0.0
2,136.881960,0.296127,0.125058,0.0,1.0,0.0,1.0,0.0
3,80.534719,0.124801,0.159243,0.0,0.0,1.0,0.0,0.0
4,120.041158,0.098129,0.027542,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
9995,58.366442,0.066366,0.086344,0.0,0.0,1.0,0.0,0.0
9996,139.502160,0.119014,0.285680,0.0,0.0,0.0,1.0,0.0
9997,71.012122,0.119204,0.262262,0.0,1.0,0.0,1.0,0.0
9998,21.031405,0.027088,0.295243,0.0,0.0,0.0,0.0,0.0
9999,54.028632,0.096438,0.042823,1.0,0.0,0.0,0.0,0.0

In [68]:
X=transformed_df.copy()

In [69]:
X

,num__amount,num__device_risk_score,num__ip_risk_score,cat__transaction_type_ATM,cat__transaction_type_Online,cat__merchant_category_Clothing,cat__merchant_category_Travel,cat__country_NG,remainder__is_fraud
0,4922.587542,0.992347,0.947908,1.0,0.0,0.0,1.0,0.0,1
1,48.018303,0.168571,0.224057,0.0,0.0,0.0,0.0,0.0,0
2,136.881960,0.296127,0.125058,0.0,1.0,0.0,1.0,0.0,0
3,80.534719,0.124801,0.159243,0.0,0.0,1.0,0.0,0.0,0
4,120.041158,0.098129,0.027542,0.0,1.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...
9995,58.366442,0.066366,0.086344,0.0,0.0,1.0,0.0,0.0,0
9996,139.502160,0.119014,0.285680,0.0,0.0,0.0,1.0,0.0,0
9997,71.012122,0.119204,0.262262,0.0,1.0,0.0,1.0,0.0,0
9998,21.031405,0.027088,0.295243,0.0,0.0,0.0,0.0,0.0,0
9999,54.028632,0.096438,0.042823,1.0,0.0,0.0,0.0,0.0,0

In [74]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [76]:
print("Before SMOTE:")
print(y_train.value_counts(), "\n")
smote = SMOTE(random_state=42)

Before SMOTE:
is_fraud
0    7613
1     387
Name: count, dtype: int64

In [77]:
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)
print("After SMOTE:")
print(pd.Series(y_train_resampled).value_counts(), "\n")

After SMOTE:
is_fraud
1    7613
0    7613
Name: count, dtype: int64

In [82]:
X_train_resampled.to_csv("xtrain_data.csv")

In [83]:
y_train_resampled.to_csv("ytrain_data.csv")

In [84]:
X_test.to_csv("xtesting_data.csv")

In [85]:
y_test.to_csv("ytest_data.csv")

In [89]:
y_train.shape

(8000,)

In [87]:
X_test.shape

(2000, 9)

In [88]:
X_train.shape

(8000, 9)

In [90]:
import joblib

In [91]:
joblib.dump(preprocessor,"preprocessor.joblib")

['preprocessor.joblib']